---
## 网站配置
logo: 
  ## 网站名称
  title: "Pear Admin"
  ## 网站图标
  image: "admin/images/logo.png"
## 菜单配置
menu: 
  ## 菜单数据来源
  data: "admin/data/menu.json"
  ## 菜单接口的请求方式 GET / POST
  method: "GET" 
  ## 是否同时只打开一个菜单目录
  accordion: true
  ## 侧边默认折叠状态
  collaspe: false
  ## 是否开启多系统菜单模式
  control: false
  ## 顶部菜单宽度 PX
  controlWidth: 500
  ## 默认选中的菜单项
  select: "10"
  ## 是否开启异步菜单，true 时 data 属性设置为菜单数据，false 时为 json 文件或后端接口
  async: true
## 视图内容配置
tab: 
  ## 是否开启多选项卡
  muiltTab: true
  ## 保持视图状态
  keepState: true
  ## 开启选项卡记忆
  session: true
  ## 最大可打开的选项卡数量
  tabMax: "30"
  ## 首页
  index: 
    id: "10" ## 标识 ID , 建议与菜单项中的 ID 一致
    href: "view/console/console1.html" ## 页面地址
    title: "首页" ## 标题
## 主题配置
theme: 
  ## 默认主题色，对应 colors 配置中的 ID 标识
  defaultColor: "2"
  ## 默认的菜单主题 dark-theme 黑 / light-theme 白
  defaultMenu: "dark-theme"
  ## 是否允许用户切换主题，false 时关闭自定义主题面板
  allowCustom: true
## 主题色配置列表
colors: 
- id: "1"
  color: "#2d8cf0"
- id: "2"
  color: "#36b368"
- id: "3"
  color: "#f6ad55"
- id: "4"
  color: "#f56c6c"
- id: "5"
  color: "#3963bc"
## 主题面板的链接列表
links: 
- icon: "layui-icon layui-icon-website"
  title: "官方网站"
  href: "http://www.pearadmin.com"
- icon: "layui-icon layui-icon-read"
  title: "开发文档"
  href: "http://www.pearadmin.com/doc/"
- icon: "layui-icon layui-icon-fonts-code"
  title: "开源地址"
  href: "https://gitee.com/pear-admin/Pear-Admin-Layui/"
- icon: "layui-icon layui-icon-survey"
  title: "问答社区"
  href: "http://forum.pearadmin.com/"
## 其他配置
other: 
  ## 主页动画时长
  keepLoad: "1200"
  ## 布局顶部主题
  autoHead: false
## 头部配置
header:
  ## 站内消息，通过 false 设置关闭
  message: "admin/data/message.json"